apiVersion: v1
kind: PersistentVolume
metadata:
  name: verdaccio-pv
  annotations:
    pv.beta.kubernetes.io/gid: "101"
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/liuhaoran/kubemount/verdaccio
    type: Directory
  persistentVolumeReclaimPolicy: Retain