apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: redis-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: redis-sc
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - {key: environment, operator: In, values: [dev]}