apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test-store
  namespace: dev
spec:
  type: state.redis
  version: v1
  metadata:
  # - name: keyPrefix
  #   value: name
  - name: redisHost
    value: redis-master.dapr-system.svc.cluster.local:6379
  - name: redisPassword
    value: test-redis
    # secretKeyRef:
    #   name: dapr-redis-secret
    #   key: PASSWORD
  # uncomment below for connecting to redis cache instances over TLS (ex - Azure Redis Cache)
  # - name: enableTLS
  #   value: true 