kind: Service
apiVersion: v1
metadata:
  name: dapr-node-client
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer