apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: redis-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath